name: Reporte de Bug
title: "Bug - "
description: Plantilla para registrar un Bug que afecta a la aplicaci칩n web.
labels: ["bug"]
projects: ["PlayerCodeDev/7"]
assignees:
  - PlayerCodeDev
body:
  - type: markdown
    attributes:
      value: |
        ### Reporte de Bug

        A침ade y completa la siguente informaci칩n de forma clara y precisa para solucionar el problema.

  - type: input
    id: affected-part
    attributes:
      label: Parte Afectada
      description: 쮻칩nde ocurre el error? (p치gina, componenete, endpoint, etc.).
      placeholder: "Ej: P치gina de login / GET /api/movies"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Descripci칩n del Problema
      description: Describe clara y detalladamente el error observado.
      placeholder: "Al intentar iniciar sesi칩n con credenciales v치lidas, se muestra un error 500..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Pasos para Reproducir el Error
      description: Explica c칩mo se puede reproducir el bug paso a paso.
      placeholder: |
        1. Ir a la p치gina de login.
        2. Ingresar email y contrase침a v치lidos.
        3. Hacer clic en "Iniciar sesi칩n".
        4. Aparece error 500 en consola.
      validations:
        required: true

  - type: dropdown
    id: severaty
    attributes:
      label: Severidad
      description: 쯈u칠 impacto tiene este error en la aplicaci칩n?
      options:
        - Cr칤tico 游린 (rompe funcionalidad principal)
        - Alto 游릲 (afecta la experiencia del usuario)
        - Medio 游릳 (funcional, pero molesto)
        - Bajo 游릴 (detalle menor o visual)
      default: 2

  - type: textarea
    id: additional-info
    attributes:
      label: Informaci칩n Adicional (opcional)
      description: Adjunta logs, capturas, enlaces o cualquier otra informaci칩n 칰til.
      placeholder: |
        - Mensaje de error: `Cannot read property email of undefined`
        - Captura de pantalla: [Adjuntar aqu칤]
